email_utils.py
main.py
tests/test_email_utils.py

Still need to remove the `break` keyword. so far only testing 1 email, but it's working! See below for the record that's getting pulled into the postgres db.
```
{'subject': ['Thank you for your interest in Meta'], 'from_name': ['testname@meta.com'], 'fromdomain_match': ['meta.com'], 'top_word_company_proxy': ['Meta'], 'received_at': ['Tue, 17 Dec 2024 21:14:22 +0000']}
```

Replace email utils in main

---

CONTRIBUTING.md

Added a new contributing file that includes: 
- Welcome message
- Code of Conduct
- Steps for contributions
- Submitting a bug report
More could be added as the project grows. 
Closes #31

add a contributing guidelines document

---

docs/use_cases/spec.sample.md

if you can take the google docs and convert into a markdown file, that'd be amazing!!

add spec template

---

.github/workflows/frontend-checks.yml

- Create GitHub Action workflow to check frontend code on PR's to main
- The workflow:
- Checks if frontend builds
- Lints frontend
- Checks if frontend code is formatted correctly

Create gha workflow for frontend code

---

.github/workflows/pytest.yml
.gitignore
backend/.env.example
backend/config.py
frontend/.env.sample

- Modified backend and backend .env sample/example files
- Update config.py to read APP_URL from newly modified.env
- Updated .gitignore to ignore .env files

env file configurations

---

backend/db/companies.py

Created model companies.py

---

.github/ISSUE_TEMPLATE/bug_issue_template.yml

Fixes #34 
1. Template only, no changes to app

add template from ruby for good thx

---

.github/ISSUE_TEMPLATE/feature_request_template.yml

Fixes #35 
1. Adds a feature request template for open source contributors and users to share ideas in GitHub

add new feature request template thx ruby

---

.github/ISSUE_TEMPLATE/docs_issue_template.yml

Fixes #36 
1. Adds ability for someone to report bad or missing documentation 

add docs template thx ruby

---

backend/constants.py

improve loading time by limiting lookback 90 days
[issue 212](https://github.com/lnovitz/jobseeker-analytics/issues/212)
DEFAULT_DAYS_AGO = 90
- should deliver Success page download option faster
- 
---

improve loading time by limiting lookback 90 days

---

frontend/tests/navbar.test.ts

Test to check if the navbar renders properly, navigates to home when clicking the brand logo, contains the GitHub link, has a theme switch button, contains the Sponsor button with the correct link, and displays the logout button on the success page navbar.

Navbar Tests PR

---

frontend/tests/homepage.test.ts

These tests were written by @m-banthwan . Tests for the homepage to check if the Google Login button, Website Email link, and YouTube Demo Video link are visible on the screen.

Homepage Tests PR

---

frontend/tests/success.test.ts

Test to check if the success message and download button are displayed and if the download button has the correct link.

Success Page Tests PR

---

frontend/tests/login.test.ts

Test to check if the Login button is displayed in the homepage navbar and navigates to Google auth.

Login Tests PR

---

frontend/package-lock.json
frontend/package.json

Install @playwright/test for fe tests.
1.  package.json updated
2.  package.lock.json updated
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

install missing dependencies for fe tests

---

backend/login/google_login.py
backend/main.py
frontend/utils/navbar-utils.ts

- Modified backend code to route to frontend pages
- Modified main.py to only allow origins from .env file (localhost:3000 in dev, and jobba.help in prod...) <- basically whatever is defined in the .env file
- Deleted unused function (file)
https://github.com/users/lnovitz/projects/5?pane=issue&itemId=99431048&issue=lnovitz%7Cjobseeker-analytics%7C223
Issue: #223 
Fixes #
- Modified backend code to route to frontend pages
- Modified main.py to only allow origins from .env file (localhost:3000 in dev, and jobba.help in prod...) <- basically whatever is defined in the .env file
- Deleted unused function (file)
- start on frontend homepage (localhost3000)
- login with google
- land on frontend processing page (localhost3000)
- get rerouted to frontend success page …

Routing fixes

---

backend/email_query_filters/applied_email_filter.yaml
backend/tests/test_constants.py
backend/tests/test_filter_schema.py

Fixes #236 
1. Added subject line filters `next step` and `interview` to email filter for gmail API
2. removed unnecessary characters for referral email `ve been referred` to `been referred`
3. removed github notifications email
4. Remove luma event confirmations / reminders
5. Remove sales emails % off
6. Remove newsletter emails
7. Add linkedin inmail messages to capture inbound recruiter messages (stuff you didn't apply to but could be in the interview pipeline for anyway)
- send yourself an email with an empty body with the subject line "interview"
- send yourself an email with an empty body with the subject line "next steps"
- go to http://localhost:3000/
- login with google
- download the CSV and search for the 2 emails you sent
- 
- 
- 
- 
- 
- 
- 
- 
- …

add next step and interview emails

---

backend/db/user_jobs.py

Create User Jobs Model

---

backend/db/users.py

Create Users Model

---

backend/db/user_session.py

Created a UserSession model using SQLModel
Fixes #232 
1. Created UserSession model using SQLModel
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

Created UserSession model

---

.github/workflows/frontend-checks.yml

trigger frontend workflow only when frontend files are changed
none
1. Modified frontend-checks.yml (GHA)
2. Triggers only when files inside frontend directory are modified.
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

trigger frontend workflow only when frontend files are changed

---

backend/config.py
backend/login/google_login.py
backend/main.py
backend/session/session_layer.py
backend/tests/test_config_utils.py
backend/utils/cookie_utils.py

Recap of the frontend to backend talk issue below.
Backend API: https://staging-jobba-help-backend.onrender.com
Frontend: https://staging-jobba-help.onrender.com
Error when accessing my processing endpoint: Access to fetch at 'https://staging-api.jobba.help/processing' from origin 'https://www.staging.jobba.help' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
What I've tried:
I configured CORS middleware in my FastAPI application to allow requests from specific origins: https://github.com/lnovitz/jobseeker-analytics/pull/258/files#r1985363388
Despite the CORS middleware configuration, the …

conditional cookies noms

---

backend/.env.example
backend/db/users.py
backend/db/utils/user_utils.py
backend/login/google_login.py
backend/main.py
backend/utils/auth_utils.py

Fixes #243
1. Implemented user_exists and add_user function
2. Created Pydantic model for Users
- 
- 
- 
- OS: 
- 
- 
- Added start_date attribute to Users
- Added API endpoint to add user into the database
- 
- 
- 
- 
- 
---

Create new user

---

backend/main.py

Added the functionality that reads the data from UserEmails and returns the JSON format.
Fixes #
1. 
2. 
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

Fetch from user email

---

backend/main.py
backend/session/session_layer.py
frontend/app/success/page.tsx

Backend code fixes for login and cookies
1. Modified logout function to redirect to frontend homepage
2. Cookie stuff in validation depending on environment
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

Fix backend code

---

frontend/app/processing/page.tsx

Go to dashboard page instead of success page after processing
Fixes #
1. 
2. 
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

fix routing

---

frontend/components/spinner.tsx
frontend/tests/spinner.test.ts

These tests were written by @m-banthwan . Test to check if the Spinner is visible.

Spinner Tests PR

---

backend/main.py
backend/routes/auth.py

**Pls review PR #273 before this as this PR builds on top of it.**
Move login and logout related code into routes/auth.py
1. Move logout functionality into auth.py
2. Move login/google_login.py functions into auth.py
3. Fix imports in main.py

Create routes/auth.py for login and logout functionality

---

backend/utils/email_utils.py

hte -> the
1. 
2. 
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

chore: update email_utils.py

---

backend/database.py
backend/main.py
backend/routes/email_routes.py

Fix refactoring bug...
Move processing endpoint to email_routes.py bc of api_call_finished global variable.
Processing endpoint relies on the api_call_finished global variable, which is updated by the fetch functions. So to make life easy just put it in the same file.
1. Move processing endpoint to email_routes.py
2. Move processing global variable api_call_finished to email_routes.py as its used by both functions

Refactor fixes

---

.gitignore
CONTRIBUTING.md

updating contributing with troubleshooting message
Fixes #
1. 
2. 
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

updated contributing

---

backend/routes/users_routes.py

```
backend-1   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend-1   |   File "/app/main.py", line 24, in <module>
backend-1   |     from routes import playground_routes, email_routes, auth_routes, file_routes, users_routes
backend-1   |   File "/app/routes/users_routes.py", line 4, in <module>
backend-1   |     from db.user_email import UserEmail
```
Backend wasn't spinning up locally
Fixes #293 
1. 
2. 
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

mis import

---

backend/constants.py
backend/routes/email_routes.py
backend/utils/llm_utils.py

- Increase the rate limit so more emails can be processed faster. New model gemini-2.0-flash-lite has a rate limit of 30 responses / minute
- also limited to 30 days instead of 90 days of data
- defaulted values to unknown if LLM couldn't process job title, etc.
Fixes #316 
1. Switch out llm model
- 
- 
- 
- OS: 
- 
- 
- 
- Google Gemini API model change
- faster processing of emails
- 
- 
- 
- 
---

update to gemini 2.0 flash lite

---

backend/email_query_filters/applied_email_filter.yaml

Subject line emails with "next steps" will also be captured. Unfortunately gmail API does not support wildcard filters.
Fixes #236 
1. Updated `applied_email_filter.yaml`
2. 
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

next steps should also be captured

---

backend/routes/email_routes.py
frontend/app/processing/page.tsx

Add processing status on processing page
Fixes #326 
1. Add progress bar with status in % to display on email process progress on processing page
2. Calculate progress by: (processed_emails/total_emails)*100 
3. Send # of processed_emails and total_emails to the frontend in processing response
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

display email processing progress on process page

---

frontend/app/page.tsx

Fixes #
1. 
2. 
3. 
Before:
After:
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

Redo homepage

---

frontend/app/dashboard/page.tsx

fix dashboard table styling
Fixes #312 
1.  Change tailwindcss styling for dashboard table

fix dashboard

---

frontend/app/page.tsx
frontend/components/icons.tsx

refactor hompage to use heroui components for app consistency
1. move svg to icons.tsx
2. use card, button, checkbox, input components from heroUI
3. remove <head> tag bc it doesn't do anything since all that info is defined in layout.tsx

refactor hompage to use heroui components

---

frontend/components/navbar.tsx

enlarge logo text and add bottom border to navbar
1. make logo text size 2xl
2. add bottom border to header
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

enlarge logo text and add bottom border to navbar

---

.github/dependabot.yml

Fixes #
1. 
2. 
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

specify package ecosystems

---

.github/dependabot.yml

Dependabot is a bit noisy. This will disable pull requests that aren't tied to a vulnerabaility of some kind.
Relates to #411
1. Disables non-vulnerability dependency upgrades by Dependabot
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates#overriding-the-default-behavior-with-a-configuration-file
- 
- 
- 
---

Disable pull requests from dependabot that aren't security related

---

backend/config.py
backend/main.py
backend/utils/cookie_utils.py

Fixes #
1. 
2. 
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
- 
- 
- 
- 
- 
---

add origin settings

---

backend/config.py
backend/routes/email_routes.py
backend/utils/llm_utils.py

Enhanced email labels
- updates LLM prompt with labels from my hand labeled data #414 
- adds condition to check for false positives and does not add email to database if not related to job app
Before
After
---

Better labels, remove non-job-related emails

---

.github/workflows/assign.yml

- Attempts to keep momentum for contributors moving by asking for updates within a month
Fixes #426 
1. Add github workflow yml
- https://github.com/takanome-dev/assign-issue-action
- the workflow only has permissions to write to issues, it does not have code access.
- 
- 
---

manage stale issues with reminders

---

.gitignore

Adding .idea/ to the gitignore file for anyone using JetBrains products.
---

Add .idea to gitignore file

---

backend/email_query_filters/applied_email_filter.yaml

Fixes #464 
1. Added "support@userinterviews.com" to the backend/email_query_filters/applied_email_filter.yaml file.
2. 
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
---

added support@userinterviews.com

---

.github/workflows/assign-test.yml

Fixes #
1. 
2. 
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
---

change to 1 min

---

.github/workflows/assign-test.yml

Fixes #
1. 
2. 
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
---

help wanted

---

frontend/app/processing/page.tsx

Fixes #548 
1. 
2. 
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
---

check for 0 processed emails

---

backend/routes/file_routes.py
frontend/app/dashboard/page.tsx
frontend/components/JobApplicationsDashboard.tsx

Renders Sankey diagram directly in the dashboard app and moves the download button into the Sankey chart header. This provides a much better user experience by showing the flow visualization immediately without requiring a separate download. The implementation includes proper date range watermarks and consistent styling between the interactive view and downloadable PNG.
1. **Frontend Sankey Integration**: Added Sankey chart rendering directly in the dashboard using recharts library
2. **Backend Data Refactoring**: Created `get_sankey_data_dict()` function to share data logic between PNG export and JSON API
3. **New API Endpoint**: Added `/get-sankey-data` endpoint to provide Sankey data for frontend consumption
4. **Consistent Styling**: Updated PNG generation to match dashboard colors …

Sankey render dashboard

---

frontend/app/dashboard/page.tsx
frontend/components/JobApplicationsDashboard.tsx

Added company name search functionality to the dashboard, allowing users to quickly filter their job applications by company name. This improves the user experience by making it easier to find specific applications without scrolling through the entire list.
Fixes #560 
1. **Frontend Search State**: Added `searchTerm` and `filteredData` state management in dashboard page
2. **Real-time Filtering**: Implemented useEffect hook to filter data based on company name search
3. **Search Input UI**: Added search input field to JobApplicationsDashboard component with proper styling
4. **Component Interface**: Updated JobApplicationsDashboardProps interface to include search functionality
5. **Responsive Design**: Search input is responsive and supports both light and dark themes
6. …

[FEAT]: Search by company name

---

frontend/data/contributors.json

Add my name to the contriburtors page
Added my information to the contributors.json
Before : 
After :
- 
- 
- 
- OS: 
- 
- 
- 
- 
---

DOC/Adding name to contributor list.

---

frontend/data/contributors.json

Completed the workshop successfully and added the name to the list
Fixes #
1. 
2. 
3. 
- 
- 
- 
- OS: 
- 
- 
- 
- 
---

Completed the workshop successfully and adding name to the list
